---
deployment:
  tasks:

    # ==============================
    # FRONTEND
    # ==============================

    - export PUBLIC_HTML=/home/$USER/public_html

    # Clean old frontend files
    - /bin/rm -rf $PUBLIC_HTML/assets
    - /bin/rm -f $PUBLIC_HTML/index.html
    - /bin/rm -f $PUBLIC_HTML/_redirects
    - /bin/rm -f $PUBLIC_HTML/.htaccess
    - /bin/rm -f $PUBLIC_HTML/robots.txt
    - /bin/rm -f $PUBLIC_HTML/sitemap.xml

    # Deploy frontend build
    - /bin/cp -R dist/assets $PUBLIC_HTML/
    - /bin/cp dist/index.html $PUBLIC_HTML/
    - /bin/cp dist/.htaccess $PUBLIC_HTML/
    - /bin/cp dist/_redirects $PUBLIC_HTML/
    - /bin/cp dist/robots.txt $PUBLIC_HTML/
    - /bin/cp dist/sitemap.xml $PUBLIC_HTML/
    - /bin/cp dist/logo.png $PUBLIC_HTML/


    # ==============================
    # BACKEND
    # ==============================

    - export BACKEND_DIR=/home/$USER/backend_app

    - /bin/mkdir -p $BACKEND_DIR

    # Backend compiled files
    - /bin/cp -R backend/dist $BACKEND_DIR/

    # Backend package files
    - /bin/cp backend/package.json $BACKEND_DIR/
    - /bin/cp backend/package-lock.json $BACKEND_DIR/

    # Install production dependencies
    - /usr/local/bin/npm install --prefix $BACKEND_DIR --omit=dev --no-audit --no-fund