---
deployment:
  tasks:

    # ==============================
    # FRONTEND
    # ==============================

    # Clean old frontend files
    - /bin/rm -rf /home/click2itbd/public_html/assets
    - /bin/rm -f /home/click2itbd/public_html/index.html
    - /bin/rm -f /home/click2itbd/public_html/_redirects
    - /bin/rm -f /home/click2itbd/public_html/.htaccess
    - /bin/rm -f /home/click2itbd/public_html/robots.txt
    - /bin/rm -f /home/click2itbd/public_html/sitemap.xml

    # Deploy frontend build
    - /bin/cp -R dist/assets /home/click2itbd/public_html/
    - /bin/cp dist/index.html /home/click2itbd/public_html/
    - /bin/cp dist/.htaccess /home/click2itbd/public_html/
    - /bin/cp dist/_redirects /home/click2itbd/public_html/
    - /bin/cp dist/robots.txt /home/click2itbd/public_html/
    - /bin/cp dist/sitemap.xml /home/click2itbd/public_html/
    - /bin/cp dist/logo.png /home/click2itbd/public_html/


    # ==============================
    # BACKEND
    # ==============================

    - /bin/mkdir -p /home/click2itbd/backend_app

    # Backend package files
    - /bin/cp backend/package.json /home/click2itbd/backend_app/
    - /bin/cp backend/package-lock.json /home/click2itbd/backend_app/
    
    # We skip copying backend/dist because it's in .gitignore and crashes the pipeline if missing.
    # - /bin/cp -R backend/dist /home/click2itbd/backend_app/

    # Install production dependencies
    - /usr/local/bin/npm install --prefix /home/click2itbd/backend_app --omit=dev --no-audit --no-fund