export const DEFAULT_HOSTING_FEATURES = [
  { id: 'disk_space', name: 'Storage Space', category: 'Standard Features', type: 'text', order: 1 },
  { id: 'bandwidth', name: 'Bandwidth', category: 'Standard Features', type: 'text', order: 2 },
  { id: 'addon_domains', name: 'Addon Domains', category: 'Standard Features', type: 'text', order: 3 },
  { id: 'subdomains', name: 'Subdomains', category: 'Standard Features', type: 'text', order: 4 },
  { id: 'emails', name: 'Email Accounts', category: 'Email & DB', type: 'text', order: 5 },
  { id: 'databases', name: 'MySQL Databases', category: 'Email & DB', type: 'text', order: 6 },
  { id: 'free_ssl', name: 'Free SSL Certificate', category: 'Security', type: 'boolean', order: 7 },
  { id: 'litespeed', name: 'LiteSpeed Web Server', category: 'Server', type: 'boolean', order: 8 },
  { id: 'daily_backup', name: 'Daily Backup', category: 'Security', type: 'boolean', order: 9 },
  { id: 'cpanel', name: 'cPanel Control Panel', category: 'Server', type: 'boolean', order: 10 },
  { id: 'softaculous', name: 'Softaculous', category: 'Server', type: 'boolean', order: 11 },
  { id: 'max_accounts', name: 'Maximum amount of hosting accounts', category: 'CloudLinux License', type: 'text', order: 12 },
  { id: 'lve_limits', name: 'Resources limits (LVE)', category: 'CloudLinux License', type: 'boolean', order: 13 },
  { id: 'cagefs', name: 'CageFS', category: 'CloudLinux License', type: 'boolean', order: 14 },
  { id: 'mysql_governor', name: 'MySQL Governor', category: 'CloudLinux License', type: 'boolean', order: 15 },
  { id: 'php_selector', name: 'PHP Selector', category: 'CloudLinux License', type: 'boolean', order: 16 },
  { id: 'ruby_selector', name: 'Ruby Selector', category: 'CloudLinux License', type: 'boolean', order: 17 },
  { id: 'python_selector', name: 'Python Selector', category: 'CloudLinux License', type: 'boolean', order: 18 },
  { id: 'nodejs_selector', name: 'NodeJS Selector', category: 'CloudLinux License', type: 'boolean', order: 19 },
  { id: 'hardened_php', name: 'HardenedPHP', category: 'CloudLinux License', type: 'boolean', order: 20 },
  { id: 'apache_mod_lsapi_pro', name: 'Apache mod_lsapi PRO', category: 'CloudLinux License', type: 'boolean', order: 21 },
  { id: 'secure_links', name: 'SecureLinks (symlink protection)', category: 'CloudLinux License', type: 'boolean', order: 22 },
  { id: 'website_monitoring', name: 'Website monitoring tool', category: 'CloudLinux License', type: 'boolean', order: 23 },
  { id: 'slow_site_analyzer', name: 'Slow Site analyzer', category: 'CloudLinux License', type: 'boolean', order: 24 },
  { id: 'php_xray', name: 'PHP X-Ray', category: 'CloudLinux License', type: 'boolean', order: 25 },
  { id: 'centralized_monitoring', name: 'Centralized Monitoring', category: 'CloudLinux License', type: 'boolean', order: 26 },
  { id: 'accelerate_wp', name: 'AccelerateWP', category: 'CloudLinux License', type: 'boolean', order: 27 },
  { id: 'support_247', name: 'Support 24/7', category: 'CloudLinux License', type: 'boolean', order: 28 }
];

export const DEFAULT_HOSTING_PACKAGES = [
  // 1. Shared cPanel Tier
  {
    id: 'plan_student',
    name: 'Student',
    slug: 'student',
    category: 'shared',
    order: 1,
    status: 'published',
    badge: 'Budget Friendly',
    priceOverride: true,
    overridePrice: 75,
    overrideAnnualPrice: 720,
    pricing: { licenseCostUsd: 0, monthly: 75, annually: 720, billingCycle: 'monthly' },
    cloudLinuxLimits: { cpu: '100', pmem: '1024', vmem: '2048', io: '10', iops: '1024', ep: '20', nproc: '100', inodes: '150000' },
    comparisonValues: {
      disk_space: '2 GB NVMe SSD',
      bandwidth: '50 GB',
      addon_domains: '0',
      subdomains: '3',
      emails: '2',
      databases: '2',
      free_ssl: true,
      litespeed: true,
      daily_backup: false,
      cpanel: true,
      softaculous: true
    },
    popular: false,
    allowCustomization: false
  },
  {
    id: 'plan_starter',
    name: 'Starter',
    slug: 'starter',
    category: 'shared',
    order: 2,
    status: 'published',
    badge: 'Standard Starter',
    priceOverride: true,
    overridePrice: 150,
    overrideAnnualPrice: 1440,
    pricing: { licenseCostUsd: 0, monthly: 150, annually: 1440, billingCycle: 'monthly' },
    cloudLinuxLimits: { cpu: '100', pmem: '1024', vmem: '2048', io: '10', iops: '1024', ep: '20', nproc: '100', inodes: '250000' },
    comparisonValues: {
      disk_space: '5 GB NVMe SSD',
      bandwidth: '100 GB',
      addon_domains: '0',
      subdomains: 'Unlimited',
      emails: '5',
      databases: '5',
      free_ssl: true,
      litespeed: true,
      daily_backup: false,
      cpanel: true,
      softaculous: true
    },
    popular: false,
    allowCustomization: false
  },
  {
    id: 'plan_standard',
    name: 'Standard',
    slug: 'standard',
    category: 'shared',
    order: 3,
    status: 'published',
    badge: 'Most Popular',
    priceOverride: true,
    overridePrice: 350,
    overrideAnnualPrice: 3360,
    pricing: { licenseCostUsd: 0, monthly: 350, annually: 3360, billingCycle: 'monthly' },
    cloudLinuxLimits: { cpu: '150', pmem: '2048', vmem: '4096', io: '20', iops: '2048', ep: '30', nproc: '150', inodes: '500000' },
    comparisonValues: {
      disk_space: '10 GB NVMe SSD',
      bandwidth: 'Unlimited',
      addon_domains: '3',
      subdomains: 'Unlimited',
      emails: '20',
      databases: '20',
      free_ssl: true,
      litespeed: true,
      daily_backup: true,
      cpanel: true,
      softaculous: true
    },
    popular: true,
    allowCustomization: true
  },
  {
    id: 'plan_professional',
    name: 'Professional',
    slug: 'professional',
    category: 'shared',
    order: 4,
    status: 'published',
    badge: 'Business Boost',
    priceOverride: true,
    overridePrice: 650,
    overrideAnnualPrice: 6240,
    pricing: { licenseCostUsd: 0, monthly: 650, annually: 6240, billingCycle: 'monthly' },
    cloudLinuxLimits: { cpu: '200', pmem: '4096', vmem: '8192', io: '30', iops: '4096', ep: '50', nproc: '200', inodes: '750000' },
    comparisonValues: {
      disk_space: '20 GB NVMe SSD',
      bandwidth: 'Unlimited',
      addon_domains: '10',
      subdomains: 'Unlimited',
      emails: 'Unlimited',
      databases: 'Unlimited',
      free_ssl: true,
      litespeed: true,
      daily_backup: true,
      cpanel: true,
      softaculous: true
    },
    popular: false,
    allowCustomization: true
  },
  {
    id: 'plan_premium',
    name: 'Premium',
    slug: 'premium',
    category: 'shared',
    order: 5,
    status: 'published',
    badge: 'Maximum Power',
    priceOverride: true,
    overridePrice: 1200,
    overrideAnnualPrice: 11520,
    pricing: { licenseCostUsd: 0, monthly: 1200, annually: 11520, billingCycle: 'monthly' },
    cloudLinuxLimits: { cpu: '300', pmem: '8192', vmem: '16384', io: '50', iops: '8192', ep: '100', nproc: '300', inodes: '1000000' },
    comparisonValues: {
      disk_space: '50 GB NVMe SSD',
      bandwidth: 'Unlimited',
      addon_domains: 'Unlimited',
      subdomains: 'Unlimited',
      emails: 'Unlimited',
      databases: 'Unlimited',
      free_ssl: true,
      litespeed: true,
      daily_backup: true,
      cpanel: true,
      softaculous: true
    },
    popular: false,
    allowCustomization: true
  },

  // 2. Managed WordPress Cloud Tier (BDIX Turbo)
  {
    id: 'wp_starter',
    name: 'WP Starter',
    slug: 'wp-starter',
    category: 'wordpress',
    order: 6,
    status: 'published',
    badge: 'Student & Blogger',
    priceOverride: true,
    overridePrice: 250,
    overrideAnnualPrice: 2400,
    pricing: { licenseCostUsd: 0, monthly: 250, annually: 2400, billingCycle: 'monthly' },
    cloudLinuxLimits: { cpu: '200', pmem: '2048', vmem: '4096', io: '30', iops: '2048', ep: '40', nproc: '150', inodes: '350000' },
    comparisonValues: {
      disk_space: '10 GB Pure NVMe SSD',
      bandwidth: '100 GB Premium Bandwidth',
      addon_domains: '1 Website',
      subdomains: '5',
      emails: '10',
      databases: '5',
      free_ssl: true,
      litespeed: true,
      daily_backup: true,
      cpanel: true,
      softaculous: true
    },
    popular: false,
    features: [
      '10 GB NVMe SSD',
      '2 vCPU & 2 GB RAM',
      'LiteSpeed Web Server',
      'Free SSL Certificate',
      'Daily Automated Backups',
      '1-Click WordPress',
      '24/7 Support'
    ]
  },
  {
    id: 'wp_pro',
    name: 'WP Pro Turbo',
    slug: 'wp-pro-turbo',
    category: 'wordpress',
    order: 7,
    status: 'published',
    badge: 'Most Popular',
    popular: true,
    priceOverride: true,
    overridePrice: 500,
    overrideAnnualPrice: 4800,
    pricing: { licenseCostUsd: 0, monthly: 500, annually: 4800, billingCycle: 'monthly' },
    cloudLinuxLimits: { cpu: '400', pmem: '4096', vmem: '8192', io: '50', iops: '4096', ep: '60', nproc: '250', inodes: '600000' },
    comparisonValues: {
      disk_space: '25 GB Pure NVMe SSD',
      bandwidth: 'Unlimited Bandwidth',
      addon_domains: '5 Websites',
      subdomains: 'Unlimited',
      emails: 'Unlimited',
      databases: 'Unlimited',
      free_ssl: true,
      litespeed: true,
      daily_backup: true,
      cpanel: true,
      softaculous: true
    },
    features: [
      '25 GB NVMe SSD',
      '4 vCPU & 4 GB RAM',
      'LiteSpeed Web Server',
      'Free SSL Certificate',
      'Daily Automated Backups',
      'Malware Scanner',
      'Priority Support'
    ]
  },
  {
    id: 'wp_ecom',
    name: 'E-Commerce Ultra',
    slug: 'wp-ecom-ultra',
    category: 'wordpress',
    order: 8,
    status: 'published',
    badge: 'WooCommerce Boosted',
    popular: false,
    priceOverride: true,
    overridePrice: 950,
    overrideAnnualPrice: 9120,
    pricing: { licenseCostUsd: 0, monthly: 950, annually: 9120, billingCycle: 'monthly' },
    cloudLinuxLimits: { cpu: '600', pmem: '8192', vmem: '16384', io: '80', iops: '8192', ep: '100', nproc: '400', inodes: '1000000' },
    comparisonValues: {
      disk_space: '50 GB Pure NVMe SSD',
      bandwidth: 'Unlimited Bandwidth',
      addon_domains: '10 Websites',
      subdomains: 'Unlimited',
      emails: 'Unlimited',
      databases: 'Unlimited',
      free_ssl: true,
      litespeed: true,
      daily_backup: true,
      cpanel: true,
      softaculous: true
    },
    features: [
      '50 GB NVMe SSD',
      '6 vCPU & 8 GB RAM',
      'WooCommerce Optimized',
      'Free SSL Certificate',
      'Automated Backups',
      'DDoS Protection',
      'VIP Support'
    ]
  },
  {
    id: 'wp_mega',
    name: 'Mega Portal Cloud',
    slug: 'wp-mega-portal',
    category: 'wordpress',
    order: 9,
    status: 'published',
    badge: 'Enterprise WP',
    popular: false,
    priceOverride: true,
    overridePrice: 1800,
    overrideAnnualPrice: 17280,
    pricing: { licenseCostUsd: 0, monthly: 1800, annually: 17280, billingCycle: 'monthly' },
    cloudLinuxLimits: { cpu: '800', pmem: '16384', vmem: '32768', io: '100', iops: '10240', ep: '150', nproc: '600', inodes: '2000000' },
    comparisonValues: {
      disk_space: '100 GB Enterprise NVMe',
      bandwidth: 'Unlimited Bandwidth',
      addon_domains: 'Unlimited Websites',
      subdomains: 'Unlimited',
      emails: 'Unlimited',
      databases: 'Unlimited',
      free_ssl: true,
      litespeed: true,
      daily_backup: true,
      cpanel: true,
      softaculous: true
    },
    features: [
      '100 GB NVMe SSD',
      '8 vCPU & 16 GB RAM',
      'Dedicated IP Address',
      'Free SSL Certificate',
      'Real-time Backups',
      'DDoS Protection',
      '24/7 Priority Support'
    ]
  },

  // 3. High-Performance KVM Cloud VPS Tier
  {
    id: 'vps_starter',
    name: 'Cloud VPS 1',
    slug: 'vps-starter',
    category: 'vps',
    order: 10,
    status: 'published',
    badge: 'Standard Starter',
    popular: false,
    priceOverride: true,
    overridePrice: 1800,
    overrideAnnualPrice: 17280,
    pricing: { licenseCostUsd: 0, monthly: 1800, annually: 17280, billingCycle: 'monthly' },
    cloudLinuxLimits: { cpu: '2 Cores', pmem: '4096', vmem: '4096', io: '50', iops: '5000', ep: '50', nproc: '200', inodes: '1000000' },
    comparisonValues: {
      disk_space: '60 GB NVMe SSD',
      bandwidth: '2 TB Premium Bandwidth',
      addon_domains: 'Unlimited',
      subdomains: 'Unlimited',
      emails: 'Unlimited',
      databases: 'Unlimited',
      free_ssl: true,
      litespeed: false,
      daily_backup: true,
      cpanel: false,
      softaculous: false
    },
    features: [
      'Pure NVMe Storage in RAID 10',
      '1 Dedicated Public IPv4',
      '1Gbps Network Port',
      'KVM Hardware Virtualization',
      'Automated Weekly Backups',
      '24/7 Server Monitoring'
    ]
  },
  {
    id: 'vps_standard',
    name: 'Cloud VPS 2',
    slug: 'vps-standard',
    category: 'vps',
    order: 11,
    status: 'published',
    badge: 'Most Popular',
    popular: true,
    priceOverride: true,
    overridePrice: 3500,
    overrideAnnualPrice: 33600,
    pricing: { licenseCostUsd: 0, monthly: 3500, annually: 33600, billingCycle: 'monthly' },
    cloudLinuxLimits: { cpu: '4 Cores', pmem: '8192', vmem: '8192', io: '80', iops: '8000', ep: '80', nproc: '400', inodes: '2000000' },
    comparisonValues: {
      disk_space: '120 GB NVMe SSD',
      bandwidth: '5 TB Premium Bandwidth',
      addon_domains: 'Unlimited',
      subdomains: 'Unlimited',
      emails: 'Unlimited',
      databases: 'Unlimited',
      free_ssl: true,
      litespeed: false,
      daily_backup: true,
      cpanel: false,
      softaculous: false
    },
    features: [
      'Pure NVMe Storage in RAID 10',
      '1 Dedicated Public IPv4',
      '1Gbps Network Port',
      'KVM Hardware Virtualization',
      'Automated Daily Snapshots',
      'Free OS Reinstall Anytime',
      '24/7 Priority Ticket Support'
    ]
  },
  {
    id: 'vps_pro',
    name: 'Cloud VPS 3',
    slug: 'vps-pro',
    category: 'vps',
    order: 12,
    status: 'published',
    badge: 'Heavy Production',
    popular: false,
    priceOverride: true,
    overridePrice: 6800,
    overrideAnnualPrice: 65280,
    pricing: { licenseCostUsd: 0, monthly: 6800, annually: 65280, billingCycle: 'monthly' },
    cloudLinuxLimits: { cpu: '8 Cores', pmem: '16384', vmem: '16384', io: '100', iops: '12000', ep: '120', nproc: '800', inodes: '4000000' },
    comparisonValues: {
      disk_space: '240 GB NVMe SSD',
      bandwidth: '10 TB Premium Bandwidth',
      addon_domains: 'Unlimited',
      subdomains: 'Unlimited',
      emails: 'Unlimited',
      databases: 'Unlimited',
      free_ssl: true,
      litespeed: false,
      daily_backup: true,
      cpanel: false,
      softaculous: false
    },
    features: [
      'Pure NVMe Storage in RAID 10',
      '2 Dedicated Public IPv4 Included',
      '10Gbps Network Port',
      'KVM Hardware Virtualization',
      'Automated Daily Snapshots',
      'DDoS Protection up to 500Gbps',
      'Direct DevOps Phone Support'
    ]
  },
  {
    id: 'vps_ultra',
    name: 'Cloud VPS Pro',
    slug: 'vps-ultra',
    category: 'vps',
    order: 13,
    status: 'published',
    badge: 'Enterprise Dedicated',
    popular: false,
    priceOverride: true,
    overridePrice: 12500,
    overrideAnnualPrice: 120000,
    pricing: { licenseCostUsd: 0, monthly: 12500, annually: 120000, billingCycle: 'monthly' },
    cloudLinuxLimits: { cpu: '16 Cores', pmem: '32768', vmem: '32768', io: '150', iops: '20000', ep: '200', nproc: '1500', inodes: '8000000' },
    comparisonValues: {
      disk_space: '480 GB Enterprise NVMe',
      bandwidth: '15 TB Unmetered',
      addon_domains: 'Unlimited',
      subdomains: 'Unlimited',
      emails: 'Unlimited',
      databases: 'Unlimited',
      free_ssl: true,
      litespeed: false,
      daily_backup: true,
      cpanel: false,
      softaculous: false
    },
    features: [
      'Enterprise NVMe in RAID 10',
      '2 Dedicated Public IPv4 Included',
      '10Gbps Network Port',
      'Zero Resource Contention',
      'Automated Daily Snapshots',
      'Enterprise DDoS Mitigation',
      'Direct WhatsApp DevOps Support'
    ]
  },

  // 4. CloudLinux OS License Tier
  {
    id: 'cloudlinux_solo',
    name: 'CloudLinux OS Solo',
    slug: 'cloudlinux-os-solo',
    category: 'cloudlinux_license',
    order: 11,
    status: 'published',
    badge: 'Single Account',
    popular: false,
    priceOverride: true,
    overridePrice: 1100,
    overrideAnnualPrice: 13200,
    pricing: { licenseCostUsd: 0, monthly: 1100, annually: 13200, billingCycle: 'monthly' },
    cloudLinuxLimits: {
      max_accounts: '1',
      lve_limits: 'No',
      cagefs: 'Yes',
      mysql_governor: 'No',
      php_selector: 'Yes',
      centralized_monitoring: 'No'
    },
    comparisonValues: {
      price: '৳1,100 /mo',
      max_accounts: '1',
      lve_limits: false,
      cagefs: true,
      mysql_governor: false,
      php_selector: true,
      ruby_selector: null,
      python_selector: null,
      nodejs_selector: null,
      hardened_php: null,
      apache_mod_lsapi_pro: null,
      secure_links: null,
      website_monitoring: null,
      slow_site_analyzer: null,
      php_xray: null,
      centralized_monitoring: false,
      accelerate_wp: null,
      support_247: null
    },
    features: [
      '1 Hosting Account Supported',
      'CageFS Virtualized File System',
      'PHP Selector (Multiple PHP Versions)',
      'Stable & Secure Linux Environment',
      'Instant License Activation'
    ]
  },
  {
    id: 'cloudlinux_admin',
    name: 'CloudLinux OS Admin',
    slug: 'cloudlinux-os-admin',
    category: 'cloudlinux_license',
    order: 12,
    status: 'published',
    badge: 'Up to 5 Accounts',
    popular: true,
    priceOverride: true,
    overridePrice: 1800,
    overrideAnnualPrice: 21600,
    pricing: { licenseCostUsd: 0, monthly: 1800, annually: 21600, billingCycle: 'monthly' },
    cloudLinuxLimits: {
      max_accounts: '5',
      lve_limits: 'No',
      cagefs: 'Yes',
      mysql_governor: 'No',
      php_selector: 'Yes',
      centralized_monitoring: 'No'
    },
    comparisonValues: {
      price: '৳1,800 /mo',
      max_accounts: '5',
      lve_limits: false,
      cagefs: true,
      mysql_governor: false,
      php_selector: true,
      ruby_selector: null,
      python_selector: null,
      nodejs_selector: null,
      hardened_php: null,
      apache_mod_lsapi_pro: null,
      secure_links: null,
      website_monitoring: null,
      slow_site_analyzer: null,
      php_xray: null,
      centralized_monitoring: false,
      accelerate_wp: null,
      support_247: null
    },
    features: [
      'Up to 5 Hosting Accounts Supported',
      'CageFS Virtualized File System',
      'PHP Selector (Multiple PHP Versions)',
      'Ideal for Multi-Site Admin Servers',
      'Instant License Activation'
    ]
  },
  {
    id: 'cloudlinux_shared_pro',
    name: 'CloudLinux OS Shared Pro',
    slug: 'cloudlinux-os-shared-pro',
    category: 'cloudlinux_license',
    order: 13,
    status: 'published',
    badge: 'Unlimited Power',
    popular: false,
    priceOverride: true,
    overridePrice: 2700,
    overrideAnnualPrice: 32400,
    pricing: { licenseCostUsd: 0, monthly: 2700, annually: 32400, billingCycle: 'monthly' },
    cloudLinuxLimits: {
      max_accounts: 'Unlimited',
      lve_limits: 'Yes',
      cagefs: 'Yes',
      mysql_governor: 'Yes',
      php_selector: 'Yes',
      centralized_monitoring: 'Yes'
    },
    comparisonValues: {
      price: '৳2,700 /mo',
      max_accounts: 'Unlimited',
      lve_limits: true,
      cagefs: true,
      mysql_governor: true,
      php_selector: true,
      ruby_selector: null,
      python_selector: null,
      nodejs_selector: null,
      hardened_php: null,
      apache_mod_lsapi_pro: null,
      secure_links: null,
      website_monitoring: null,
      slow_site_analyzer: null,
      php_xray: null,
      centralized_monitoring: true,
      accelerate_wp: null,
      support_247: null
    },
    features: [
      'Unlimited Hosting Accounts',
      'Resource Limits (LVE Manager)',
      'CageFS User Isolation',
      'MySQL Governor (DB Protection)',
      'PHP Selector Support',
      'Centralized Monitoring Dashboard',
      'Enterprise Density & Stability'
    ]
  }
];